name: alpine

on: [push, workflow_dispatch]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: llvm-mingw
      - name: enter the docker container and build
        run: |
          docker pull arm64v8/alpine
          docker run -i -v `pwd`/llvm-mingw:/llvm-mingw arm64v8/alpine sh -c "cd /llvm-mingw && apk add build-base cmake extra-cmake-modules ninja-build git wget && ./build-all.sh $(pwd)/install/llvm-mingw && tar -Jcf llvm-mingw.tar.xz install/llvm-mingw"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine
          path: llvm-mingw/llvm-mingw.tar.xz
