name: alpine

on: [push, workflow_dispatch]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: llvm-mingw
      - name: enter the docker container and build
        run: |
          docker pull alpine
          docker run -i -v `pwd`/llvm-mingw:/llvm-mingw alpine sh -c "cd /llvm-mingw && apk add coreutils util-linux grep findutils tar xz build-base cmake extra-cmake-modules ninja-build git wget python3 linux-headers && ./build-all.sh /llvm-mingw/install/llvm-mingw && cd /llvm-mingw/install && tar -Jcf llvm-mingw.tar.xz llvm-mingw"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine
          path: llvm-mingw/install/llvm-mingw.tar.xz

  alpine-aarch64:
    needs: [alpine]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: llvm-mingw
      - name: enter the docker container and build
        run: |
          docker pull alpine
          docker run -i -v `pwd`/llvm-mingw:/llvm-mingw alpine sh -c "apk add coreutils util-linux grep findutils tar xz build-base cmake extra-cmake-modules ninja-build git wget python3 linux-headers autoconf automake bison flex-dev && git clone https://github.com/richfelker/musl-cross-make.git && git clone https://github.com/sabotage-linux/kernel-headers.git && cd kernel-headers && wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.20.17.tar.xz && tar -Jxf linux-4.20.17.tar.xz && cd linux-4.20.17 && make allnoconfig && make headers_install_all && cd .. && ./UPDATE.sh linux-4.20.17 && VER=4.20.17 ./create-dist.sh && cd .. && mv kernel-headers/linux-headers-4.20.17.tar.xz musl-cross-make && cd musl-cross-make && tar -Jxf linux-headers-4.20.17.tar.xz && TARGET=aarch64-linux-musl make LINUX_VER=headers-4.20.17 -j8 && cd build/local/aarch64-linux-musl && make install && mv output / && export PATH=/output/bin:$PATH && cd /llvm-mingw && ./build-all.sh /llvm-mingw/install/llvm-mingw --no-runtimes --host=aarch64-linux-musl"
      - uses: actions/download-artifact@v4
        with:
          name: alpine
      - name: Unpack native toolchain
        run: |
          tar -Jxf llvm-mingw.tar.xz
          rm llvm-mingw.tar.xz
          mv llvm-mingw llvm-mingw-native
      - name: Assemble the cross-built toolchain
        run: |
          ./prepare-cross-toolchain-unix.sh $(pwd)/llvm-mingw-native $(pwd)/llvm-mingw/install/llvm-mingw
      - name: Package the toolchain
        run: |
          cd llvm-mingw/install
          mv llvm-mingw llvm-mingw-aarch64
          tar -Jcf llvm-mingw-aarch64.tar.xz llvm-mingw-aarch64
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-aarch64
          path: llvm-mingw/install/llvm-mingw-aarch64.tar.xz
