name: alpine

on: [push, workflow_dispatch]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: llvm-mingw
      - name: enter the docker container and build
        run: |
          docker pull alpine
          docker run -i -v `pwd`/llvm-mingw:/llvm-mingw alpine sh -c "cd /llvm-mingw && apk add coreutils util-linux grep findutils tar xz build-base cmake extra-cmake-modules ninja-build git wget python3 linux-headers && ./build-all.sh /llvm-mingw/install/llvm-mingw && cd /llvm-mingw/install && tar -Jcf llvm-mingw.tar.xz llvm-mingw"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine
          path: llvm-mingw/install/llvm-mingw.tar.xz

  alpine-aarch64:
    needs: [alpine]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: llvm-mingw
      - uses: actions/download-artifact@v4
        with:
          name: alpine
      - name: Unpack native toolchain
        run: |
          mv llvm-mingw.tar.xz llvm-mingw
          cd llvm-mingw
          ls -lah
          tar -Jxf llvm-mingw.tar.xz
          rm llvm-mingw.tar.xz
          mv llvm-mingw llvm-mingw-native
      - name: enter the docker container and build
        run: |
          docker pull alpine
          docker run -i -v `pwd`/llvm-mingw:/llvm-mingw alpine sh -c "apk add coreutils util-linux grep findutils tar xz build-base cmake extra-cmake-modules ninja-build git wget python3 linux-headers autoconf automake bison flex-dev rsync && cd / && wget https://skarnet.org/toolchains/cross/aarch64-linux-musl_kryo485-15.1.0.tar.xz && tar -Jxf aarch64-linux-musl_kryo485-15.1.0.tar.xz && export PATH=/aarch64-linux-musl_kryo485-15.1.0/bin:$PATH && cd /llvm-mingw && ./build-all.sh /llvm-mingw/install/llvm-mingw --no-runtimes --host=aarch64-linux-musl && ./prepare-cross-toolchain-unix.sh /llvm-mingw/llvm-mingw-native /llvm-mingw/install/llvm-mingw && cd /llvm-mingw/install && mv llvm-mingw llvm-mingw-aarch64 && tar -Jcf llvm-mingw-aarch64.tar.xz llvm-mingw-aarch64"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-aarch64
          path: llvm-mingw/install/llvm-mingw-aarch64.tar.xz
